### ISSUE TITLE
ERROR: failed to register layer: no space left on device

### ISSUE THREAD

**Issue by shaun-ba** [LibrePhotos/librephotos-docker#48] opened 2022-03-29 14:14 UTC
I have 32GB of free space, what is going on here? How much space do you expect someone to have to install a single app?

**Comment by shaun-ba** [comment] 2022-03-29 14:37
I note that the docker-compose process gets to a point whereby nothing is pulling or being extracted, but the disk is quickly filled up with 30GB of data...., what do do about this?

**Comment by derneuere** [comment] 2022-04-30 22:24
I don't think LibrePhotos is that large. An installation takes usually 10GB. As I can't reproduce it, I will close this issue.

**Closed by derneuere** 2022-04-30 22:24 UTC
