### ISSUE TITLE
Docker install not working on rpi 4 32-bit

### ISSUE THREAD

**Issue by techxapp** [LibrePhotos/librephotos-docker#97] opened 2023-05-21 07:56 UTC
I already have other apps running , so cannot install rpi image. 

So, doing setup through docker.

Getting following error on running through - docker compose up
no matching manifest for linux/arm/v8 in the manifest list entries

And following error on running 

sudo docker run -v /home/dir/Pictures/ -v /var/lib/librephotos/data/protected_media -v /var/log/librephotos/ -v /var/lib/postgresql/data -p 3000:80 -d reallibrephotos/singleton
Unable to find image 'reallibrephotos/singleton:latest' locally
latest: Pulling from reallibrephotos/singleton
docker: no matching manifest for linux/arm/v8 in the manifest list entries.

**Comment by derneuere** [comment] 2023-05-22 07:28
Duplicate of #32 
Right now, we only build arm64 and amd64.

**Closed by derneuere** 2023-05-22 07:28 UTC
